# This playbook resets Docker storage on all compute nodes in a cluster.
#
# For each node it:
# - Clears the schedulable flag
# - Resets Docker storage
# - Reboots
# - Restores the schedulable flag
# - Installs the appropriate ose-pod container image
#
# Usage example:
#
#  ansible-playbook clean_nodes_docker.yml -e cli_clusterid=CLUSTERNAME
#


- hosts: localhost
  gather_facts: no
  become: no
  user: root

  tasks:

  - name: Check for required variables
    fail:
      msg: "Please define {{ item }}"
    when: "{{ item }} is undefined"
    with_items:
    - cli_clusterid
    run_once: True

##############################################
# Cleanup compute nodes
##############################################

- hosts: "oo_clusterid_{{ cli_clusterid }}:&oo_subhosttype_compute"
  become: no
  user: root
  serial: 10%

  vars:
    roles_path: "{{ HOME }}/git/openshift-tools/ansible/roles"

  roles:
  - role: openshift_node_schedulable
    osns_is_schedulable: False
    osns_drain: True
    osns_cluster_master: "{{ groups['oo_hosttype_master'] | intersect(groups['oo_clusterid_' ~ oo_clusterid]) | first }}"

  - role: reset_docker_storage

  - role: os_reboot_server

  - role: openshift_node_schedulable
    osns_is_schedulable: True
    osns_cluster_master: "{{ groups['oo_hosttype_master'] | intersect(groups['oo_clusterid_' ~ oo_clusterid]) | first }}"

