---
parent: 'common/test_cases/origin_release.yml'
overrides:
  junit_analysis: True
  sync_repos:
    - name: "origin"
      type: "pull_request"
extensions:
  actions:
    - type: "script"
      title: "run extended tests"
      repository: "origin"
      script: |-
        export ORIGIN_COMMIT=$(git log -1 --pretty=%h)
        test/extended/clusterup.sh
