---
parent: 'common/test_cases/origin.yml'
extensions:
  actions:
    - type: "script"
      title: "run integration tests"
      repository: "origin"
      timeout: 7200
      script: |-
        OS_BUILD_ENV_PULL_IMAGE=true JUNIT_REPORT='true' hack/env make test-tools test-integration
